[package]
name = "saltbabe"
version = "0.1.0"
authors = ["javadevelopr <java.developer.cl@gmail.com>", "hskang9 <hskang9@gmail.com>"]

[dependencies]
rust-crypto = "^0.2"
rand = "^0.4"
rustc-hex = "^1.0"


