[package]
name = "saltbabe"
version = "0.1.3"
authors = ["javadevelopr <java.developer.cl@gmail.com>", "hskang9 <hskang9@gmail.com>"]
description = "tweetnacl library in pure rust"
license-file = "LICENSE"

[dependencies]
rust-crypto = "^0.2"
rand = "^0.4"
rustc-hex = "^1.0"
hex = "0.4.0"


