[package]
name = "nacl_mini"
version = "0.1.0"
authors = ["javadevelopr <java.developer.cl@gmail.com>"]
edition = "2018"

[dependencies]
rust-crypto = "^0.2"
rand = "0.4"
#serde = "1.0"
#serde_derive = "1.0"
#serde_json ="1.0"
#ethkey = { path = "../parity-ethereum/ethkey" }
rustc-hex = "1.0"


